@startuml

/` 
Singleton 
`/
class Library {
    - available_books : vector<Book>
    - borrowed_books : vector<Book>
    - users : vector<User>
    - _instance : Library*

    + Instance()
    + addBook()
    + search(s : Searchable)
    + borrowBook(s : Searchable)
    + returnBook(s : Searchable)
}

interface Searchable {

    +search()
}

class Book {
    - available : bool 
    - author : String
    - title : String

    + isAvailable()
    + search()
}

class User {
    - name : String
    - userId : int
    - books : vector<Book>

    + search()
    + addBook(b : Book)
    + removeBook(b : Book)
    + transaction(t : Transaction)
    + charge()
}

/'
The command design pattern is implemented for the Transaction interface
User invokes Transactions and Library received the command .
'/

class Client {
    - lib : Library
    + borrowBook(u : User, b : Book)
    + returnBook(u : User, b : Book)
}

interface Transaction {

    +transaction()
}

/' 
Add the book to the list of books contained by user. Also move book from available list to borrowed list in library 
'/
class BorrowTransaction {
    - user : User&
    - book : Book&
    - lib : Library&
    
    +transaction()
}

/'
Remove the book from list of books contained by user. Also move book from borrowed list in library to available list in library
'/
class ReturnTransaction {
    - user : User&
    - book : Book&
    - lib : Library&

    +transaction()
}

class LibraryException {
    - message : String

    + what()
}

class BookException {

}

class InputExcxeption {

}

class FileManager {
    - lib : Library

    + saveLibrary()
    + loadLibrary()
}

class LibraryException <<exception>>

class InputExcxeption <<exception>>
class BookException <<exception>>


Searchable <|.. Book
Searchable <|.. User
Transaction <|.. BorrowTransaction
Transaction <|.. ReturnTransaction
Transaction --> Library : Receiver
Client --> BorrowTransaction : Create
Client --> ReturnTransaction : Create
Client --> Library : Uses
Library "1" o-- "*" Book
Library "1" o-- "*" User
Library --> Searchable
User --> Book : borrows
User --> Transaction : Invokes
FileManager --> Library : Uses
BookException --|> LibraryException
InputExcxeption --|> LibraryException


@enduml