@startuml

class Library {
    - available_books : List<Book>
    - borrowed_books : List<Book>
    - users : List<User>
 
    + addBook()
    + register(s : Searchable)
}

interface Searchable {

    +search()
}

class Book {
    - title : String
    - auhor : String
    - available : bool 

    + isAvailable()
    + search()
}

class User {
    - name : String
    - userId : int
    - books : list<Book>

    + search()
    + transaction(t : Transaction)
}

/'
The command design pattern is implemented for the Transaction interface
User invokes Transactions and Library received the command .
'/

class Client {
    - library : Library
    + borrowBook(user : User, book : Book)
    + returnBook(user : User, book : Book)
    + register(s : Searchable)
}

interface Transaction {

    +transaction()
}

/' 
Add the book to the list of books contained by user. Also move book from available list to borrowed list in library 
'/
class BorrowTransaction {
    - user : User&
    - book : Book&
    - lib : Library&
    
    +transaction()
}

/'
Remove the book from list of books contained by user. Also move book from borrowed list in library to available list in library
'/
class ReturnTransaction {
    - user : User&
    - book : Book&
    - lib : Library&

    +transaction()
}

class FileManager {
    - lib : Library
    + saveLibrary()
    + loadLibrary()
}

class LibraryException <<exception>>

class BookUnavailableException <<exception>>
class BookNotFoundException <<exception>>
class UserNotFoundException <<exception>>
class InvalidInputException <<exception>>

Searchable <|.. Book
Searchable <|.. User
Transaction <|.. BorrowTransaction
Transaction <|.. ReturnTransaction
Transaction --> Library : Receiver
Client --> BorrowTransaction : Create
Client --> ReturnTransaction : Create
Client --> Library : Uses
Library "1" o-- "*" Book
Library "1" o-- "*" User
Library --> Searchable
User --> Book : borrows
User --> Transaction : Invokes
FileManager --> Library : Uses
BookUnavailableException --|> LibraryException
BookNotFoundException --|> LibraryException
UserNotFoundException --|> LibraryException
InvalidInputException --|> LibraryException
@enduml